severity_overrides:
  HIGH: error
  MEDIUM: warning
  LOW: info

exclude:
  - aws-s3-enable-logging  # Mock environment
  - aws-s3-enable-versioning  # Will enable in real environment

include_passed: true
include_ignored: false

custom_check_dir: ./policies



